organisms-about first commit
shinonome-inc/Gottyan-frontend-basic-last-assignment pull request #10
Opened 2023-01-07 15:57 UTC by yuta-frontend

## セルフチェック
- [ 〇] お手本通りの見た目であるか　ホバー時の挙動、レスポンシブ対応など要確認
- [ 〇] ブランチ名、ファイル名、クラス名、インデントなど、コーディング規則を逸脱していないか
- [ 〇] 記述の重複はないか
chromatic[http://localhost:6006/?path=/story/organisms-about--about]

2023-01-08 02:27 UTC, tomu-fujikawa reviewed
大体いい感じです！✨

messageのscssの7行目のmax-width: $breakpoint-mdはmd未満なのでlg未満になるように修正してください！(organisms/topでもmessageの別の修正が出ていて同じファイルなのに中のコードが違うとコンフリクトを起こしてしまうのでorganisms/topとorganisms/aboutのmessageのコードがおなじになるように修正してください！)

2023-01-08 02:27 UTC, tomu-fujikawa commented on src/components/molecules/message/message.html
>  </div>
最後の行は空行にしてください！

2023-01-08 02:27 UTC, tomu-fujikawa commented on src/components/organisms/about/about.scss
> +  @media screen and(max-width:$breakpoint-md) {
5行目のmax-width:$breakpoint-mdもlg未満になるようにお願いします！

2023-01-08 02:27 UTC, tomu-fujikawa commented on src/components/organisms/about/about.scss
> +    @media screen and(max-width:$breakpoint-md) {
12行目のmax-width:$breakpoint-mdもlg未満になるようにお願いします！

2023-01-12 11:29 UTC, higashiji2000 requested changes
ほとんどいい感じです！

2023-01-12 11:29 UTC, higashiji2000 commented on src/components/organisms/about/about.html
> +<div class="about">
```suggestion
<div class="about container">
```
現在横幅いっぱいに広がってしまっているので、bootstrapのcontainerを使って余白をいい感じに調整してください。

2023-01-12 11:29 UTC, higashiji2000 commented on src/components/organisms/about/about.scss
> +  margin-bottom:100px;
marginは相殺のリスクがあるので、パーツの上下方向につけるのはあまりお勧めしません。
今回のように余白を取りたい場合は padding を使っていきましょう。

```suggestion
  padding: 100px 0;
```

参考：https://coliss.com/articles/build-websites/operation/css/about-collapsing-margins.html

2023-01-12 11:29 UTC, higashiji2000 commented on src/components/organisms/about/about.scss
> +    margin-bottom:40px;
こちらもpaddingで！

2023-01-14 03:02 UTC, higashiji2000 requested changes
コンフリクトが発生しているので、解消をお願いします。

基本的には、以下のような手順になります。

このブランチで
```
git pull origin master
```
をして最新のmasterを取得し、コンフリクト部分でどちらの変更を残すかを指定、完了したら再度push

2023-01-14 03:02 UTC, Higashiji commented on src/components/organisms/about/about.scss
> +  }
```suggestion
  padding-top: 100px;
  padding-bottom: 100px;
  @media screen and(max-width:$breakpoint-lg) {
    padding-top: 40px;
    padding-bottom: 40px;
  }
```

すみません、 このような書き方の方が適切です🙏
`container` にはデフォルトで左右の `padding` がついているのですが、4方向を一度に指定するショートハンドを使うとそれを上書きしてしまうためです。

2023-01-14 12:26 UTC, higashiji2000 approved these changes
LGTMです🏋️

2023-01-14 12:26 UTC, merged